name: agentx_mobile
description: AgentX AI Mobile Assistant - Complete AI-Powered Automation Platform
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI Dependencies
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_animate: ^4.2.0+1
  glassmorphism: ^3.0.0
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  shimmer: ^3.0.0
  liquid_swipe: ^3.1.0
  page_transition: ^2.1.0
  
  # Navigation and Routing  
  go_router: ^12.1.3
  auto_route: ^7.9.2
  
  # HTTP and State Management
  http: ^1.1.0
  dio: ^5.4.0
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  get: ^4.6.6
  
  # Authentication & Security
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  local_auth: ^2.1.7
  crypto: ^3.0.3
  
  # Storage & Database
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.3.0
  
  # Device Features
  permission_handler: ^11.1.0
  device_info_plus: ^9.1.1
  battery_plus: ^4.0.2
  connectivity_plus: ^5.0.2
  geolocator: ^10.1.0
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  
  # Communication
  socket_io_client: ^2.0.3+1
  web_socket_channel: ^2.4.0
  
  # Utilities
  json_annotation: ^4.8.1
  intl: ^0.19.0
  uuid: ^4.2.1
  path_provider: ^2.1.1
  url_launcher: ^6.2.1
  share_plus: ^7.2.1
  flutter_local_notifications: ^16.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  auto_route_generator: ^7.3.2
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/avatars/
    
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SFProDisplay-Regular.ttf
        - asset: assets/fonts/SFProDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/SFProDisplay-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
