name: agentx_mobile
description: AgentX AI Mobile - Complete AI-Powered Automation Platform
publish_to: 'none' # remove if publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI Dependencies
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  glassmorphism: ^3.0.0
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  shimmer: ^3.0.0
  liquid_swipe: ^3.1.0
  page_transition: ^2.1.0

  # Navigation and Routing
  go_router: ^12.1.3
  auto_route: ^7.9.2

  # HTTP and State Management
  http: ^1.1.0
  dio: ^5.4.0
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  get: ^4.6.6

  # Authentication & Security
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  local_auth: ^2.1.7
  crypto: ^3.0.3

  # Storage & Database
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.3.0

  # Device Features
  permission_handler: ^11.1.0
  device_info_plus: ^10.1.2
  battery_plus: ^5.0.3
  connectivity_plus: ^6.0.5
  geolocator: ^12.0.0
  camera: ^0.10.6
  image_picker: ^1.0.4
  file_picker: ^8.1.4

  # Communication
  socket_io_client: ^2.0.3+1
  web_socket_channel: ^2.4.0

  # Utilities
  json_annotation: ^4.9.0
  intl: ^0.19.0
  uuid: ^4.2.1
  path_provider: ^2.1.1
  url_launcher: ^6.2.1
  share_plus: ^7.2.1
  flutter_local_notifications: ^17.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  auto_route_generator: ^7.3.2
  mockito: ^5.4.4

flutter:
  uses-material-design: true
